version: 2

sources:
  - name: erp
    description: Banco replica da nortwind.
    schema: erp_northwind
    tables:
      - name: orders
        description: Uma linha por pedido. Inclui pedidos cancelados e deletados
        columns:
          - name: order_id
            description: Chave primeria da tabela de orders
            tests:
              - unique
              - not_null
        
      - name: products

      - name: categories

      - name: suppliers